### ISSUE TITLE
Non-breaking error in dev_setup.sh script - unexpected token in package.json?

### ISSUE THREAD

**Issue by StartupSam** [tripleblindmarket/private-kit#136]
When running dev_setup.sh, got an error about an unexpected token that seems to originate in package.json. The rest of the script completed without errors, and after a yarn install the app ran correctly in emulator, so this isn't breaking anything.

This should be a very low priority issue - just creating here for the sake of reference.

System: Ubuntu 19.10
Node: 13.8.0
NPM: 6.13.6

Verbose log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/samstowers/.nvm/versions/node/v13.8.0/bin/node',
1 verbose cli   '/home/samstowers/.nvm/versions/node/v13.8.0/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose npm-session 94eb47014aa4fd5b
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall privatekit@0.5.3
7 info lifecycle privatekit@0.5.3~preinstall: privatekit@0.5.3
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 27ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 1ms
16 timing stage:runTopLevelLifecycles Completed in 75ms
17 silly saveTree privatekit@0.5.3
18 verbose stack SyntaxError: Unexpected token
18 verbose stack  in JSON at position 207831 while parsing '{
18 verbose stack   "name": "privatekit",
18 verbose stack   "version": "'
18 verbose stack     at JSON.parse (<anonymous>)
18 verbose stack     at parseJson (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
18 verbose stack     at module.exports (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/lib/utils/parse-json.js:4:10)
18 verbose stack     at parsePkgLock (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/lib/install/read-shrinkwrap.js:67:12)
18 verbose stack     at /home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/lib/install/read-shrinkwrap.js:27:22
18 verbose stack     at tryCatcher (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Holder$2._callFunction (eval at generateHolderClass (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:12:44)
18 verbose stack     at Holder$2.checkFulfillment (eval at generateHolderClass (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:27:30)
18 verbose stack     at Promise.eval (eval at thenCallback (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:4:20)
18 verbose stack     at Promise._settlePromise (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
18 verbose stack     at Promise._settlePromise0 (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
18 verbose stack     at Promise._settlePromises (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
18 verbose stack     at Promise._fulfill (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
18 verbose stack     at Promise._settlePromise (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:587:21)
18 verbose stack     at Promise._settlePromise0 (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
18 verbose stack     at Promise._settlePromises (/home/samstowers/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
19 verbose cwd /home/samstowers/Projects/private-kit
20 verbose Linux 5.3.0-40-generic
21 verbose argv "/home/samstowers/.nvm/versions/node/v13.8.0/bin/node" "/home/samstowers/.nvm/versions/node/v13.8.0/bin/npm" "install"
22 verbose node v13.8.0
23 verbose npm  v6.13.6
24 error Unexpected token
24 error  in JSON at position 207831 while parsing '{
24 error   "name": "privatekit",
24 error   "version": "'
25 verbose exit [ 1, true ]
```

**Comment by code247** [comment]
I had come across this issue. I removed package-lock.json and ran `npm install` once again and it worked fine.
