### ISSUE TITLE
[BUG] Problem when starting up the app on an AVD

### ISSUE THREAD

**Issue by satsfy** [tripleblindmarket/private-kit#859]
## Issue type

Running project for development.

## Version 
- Release build version: 1.0.0

## Affected Devices

| Brand        |  Model        | OS  |
| ------------ |:-------------:| ----:|
| Canonical | Ubuntu | 16.04 |
| Microsoft | Windows | 10 |

## Steps to reproduce

1. Clone the repository on Ubuntu 16.04.
2. Run `./dev_setup.sh` and follow it's instructions carefully.
3. Start React Native with `./1_start_react.sh`.
4. Start the app with `./2_start_android_app.sh`.
5. Try the steps above but on Windows 10.

## Expected Behavior

- When I run `./2_start_android_app.sh`, I expect an emulated Android device to open and run the app, but instead, I get an error.

I've been stuck trying to run the app on an AVD for 5 days now, can't get the app to show up on the emulated device.

I've tried tinkering with Gradle and found no success there. 

These are the logs I get when I try to run:

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-ble-advertiser: https://npmjs.com/package/react-native-ble-advertiser
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1392 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Configure project :app
Could not find release key

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'. Some candidates are: 'installDevDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'. Some candidates are: 'installDevDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/home/pc/Desktop/GuadioesDaSaude/tesdt/covid-safe-paths/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/home/pc/Desktop/GuadioesDaSaude/tesdt/covid-safe-paths/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/home/pc/Desktop/GuadioesDaSaude/tesdt/covid-safe-paths/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I am not sure which category the title should be in, so I put none.

**Comment by bananateg** [comment]
You need to use yarn run-android

**Comment by johnschoeman** [comment]
Looks like this has been addressed. Note for future readers as of the time of this comment the commands are:
```
yarn run-android-bte ## for the bluetooth version
yarn run-android-gps ## for the location based version
```
